source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '15.0'

install! 'cocoapods', :deterministic_uuids => false

target 'TimiIOS' do
    pod 'shared', :path => '../kmp/shared/'
    pod 'SwiftLint'
    pod 'KMPNativeCoroutinesCombine'
end
